package com.uav.lowaltitude.modules.device.api;

import static org.assertj.core.api.Assertions.*;
import java.util.UUID;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.core.io.ClassPathResource;
import org.springframework.transaction.support.TransactionTemplate;
import com.uav.lowaltitude.modules.device.infrastructure.DeviceMonitoringEventRepository;

/** Persistence contract shared with the isolated PostgreSQL subclass. */
class DeviceMonitoringEventTest {
    protected JdbcTemplate jdbc;
    protected TransactionTemplate tx;
    protected DeviceMonitoringEventRepository events;
    protected String id;

    @BeforeEach void setup() {
        var ds = new DriverManagerDataSource("jdbc:h2:mem:monitor_" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("CREATE TABLE ops_device(device_id VARCHAR(36) PRIMARY KEY,source_mode VARCHAR(12),simulated BOOLEAN)");
        jdbc.execute("CREATE TABLE ops_device_state(device_id VARCHAR(36) PRIMARY KEY,connectivity VARCHAR(16),work_state_code VARCHAR(32))");
        jdbc.execute("CREATE TABLE device_event_log(event_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id VARCHAR(36) UNIQUE,device_id VARCHAR(36),event_type VARCHAR(48),level_code VARCHAR(16),message TEXT,occurred_at BIGINT,simulated BOOLEAN)");
        new ResourceDatabasePopulator(new ClassPathResource("db/migration/V202609280002__device_monitoring_events.sql")).execute(ds);
        new ResourceDatabasePopulator(new ClassPathResource("db/migration/V202609280006__monitoring_closed_windows.sql")).execute(ds);
        tx = new TransactionTemplate(new DataSourceTransactionManager(ds));
        initializeDevice();
    }

    protected void initializeDevice() {
        events = new DeviceMonitoringEventRepository(jdbc);
        id = UUID.randomUUID().toString();
        jdbc.update("INSERT INTO ops_device(device_id,source_mode,simulated) VALUES (?,'replay',TRUE)", id);
        jdbc.update("INSERT INTO ops_device_state(device_id,connectivity,work_state_code) VALUES (?,'UNKNOWN',NULL)", id);
    }
    protected void accept(String kind, long at, String connection, String work) {
        tx.executeWithoutResult(s -> {
            var before = events.lock(id);
            jdbc.update("UPDATE ops_device_state SET connectivity=?,work_state_code=? WHERE device_id=?", connection,work,id);
            events.accepted(before,kind,at);
        });
    }
    protected long count(String type) { return jdbc.queryForObject("SELECT COUNT(*) FROM device_event_log WHERE device_id=? AND event_type=?",Long.class,id,type); }
    protected void flush(long at) { tx.executeWithoutResult(s -> events.flush(id,at)); }

    @Test void firstReportTransitionsAndLastWindowArePersistedOnce() {
        accept("PARAMETERS",31000,"ONLINE","0");
        accept("SENSING",32000,"ONLINE","0"); // includes a valid zero-target frame
        accept("PARAMETERS",33000,"ONLINE","1");
        assertThat(count("REPORTING_STARTED")).isEqualTo(1);
        assertThat(count("CONNECTED")).isEqualTo(1);
        assertThat(count("STATE_CHANGED")).isEqualTo(1);
        flush(59999); assertThat(count("REPORT_SUMMARY")).isZero();
        events = new DeviceMonitoringEventRepository(jdbc); // restart: no in-memory counters
        flush(60000); flush(90000);
        assertThat(count("REPORT_SUMMARY")).isEqualTo(1);
        String message = jdbc.queryForObject("SELECT message FROM device_event_log WHERE device_id=? AND event_type='REPORT_SUMMARY'",String.class,id);
        assertThat(message).contains("工参 2", "感知 1", "replay");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM device_report_window WHERE device_id=?",Long.class,id)).isZero();
    }
    @Test void rollbackLeavesNeitherStateNorEventsNorCounters() {
        assertThatThrownBy(() -> tx.executeWithoutResult(s -> {
            var before=events.lock(id);
            jdbc.update("UPDATE ops_device_state SET connectivity='ONLINE' WHERE device_id=?",id);
            events.accepted(before,"HEARTBEAT",31000);
            throw new IllegalStateException("rollback");
        })).isInstanceOf(IllegalStateException.class);
        assertThat(count("REPORTING_STARTED")).isZero();
        assertThat(jdbc.queryForObject("SELECT connectivity FROM ops_device_state WHERE device_id=?",String.class,id)).isEqualTo("UNKNOWN");
        flush(60000); assertThat(count("REPORT_SUMMARY")).isZero();
    }
    @Test void offlineAndRecoveryOnlyOnRealTransition() {
        accept("HEARTBEAT",31000,"ONLINE","0");
        for(int i=0;i<2;i++) tx.executeWithoutResult(s -> {
            var before=events.lock(id);
            jdbc.update("UPDATE ops_device_state SET connectivity='OFFLINE' WHERE device_id=?",id);
            events.changed(before,40000);
        });
        accept("HEARTBEAT",41000,"ONLINE","0");
        assertThat(count("DISCONNECTED")).isEqualTo(1);
        assertThat(count("RECOVERED")).isEqualTo(1);
        assertThat(count("STATE_CHANGED")).isZero();
    }
    @Test void sensingDoesNotImplyOnlineAndWindowsDoNotMixSources() {
        accept("SENSING",29999,"UNKNOWN",null);
        accept("STATUS",30000,"UNKNOWN",null);
        assertThat(count("CONNECTED")).isZero();
        flush(30000); assertThat(count("REPORT_SUMMARY")).isEqualTo(1);
        jdbc.update("UPDATE ops_device SET source_mode='live',simulated=FALSE WHERE device_id=?",id);
        accept("SENSING",31000,"UNKNOWN",null);
        flush(60000); assertThat(count("REPORT_SUMMARY")).isEqualTo(3);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM device_event_log WHERE device_id=? AND event_type='REPORT_SUMMARY' AND simulated=FALSE",Long.class,id)).isEqualTo(1);
    }
    @Test void concurrentReceivesAndFlushesDoNotLoseOrDuplicateCounts() throws Exception {
        var pool=Executors.newFixedThreadPool(6);
        try {
            var futures=new java.util.ArrayList<Future<?>>();
            for(int i=0;i<24;i++) futures.add(pool.submit(() -> accept("HEARTBEAT",31000,"ONLINE","0")));
            for(var f:futures) f.get(20,TimeUnit.SECONDS);
            Future<?> a=pool.submit(() -> flush(60000)), b=pool.submit(() -> flush(60000));
            a.get(20,TimeUnit.SECONDS); b.get(20,TimeUnit.SECONDS);
            assertThat(count("REPORTING_STARTED")).isEqualTo(1);
            assertThat(count("CONNECTED")).isEqualTo(1);
            assertThat(count("REPORT_SUMMARY")).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT message FROM device_event_log WHERE device_id=? AND event_type='REPORT_SUMMARY'",String.class,id)).contains("心跳 24");
        } finally { pool.shutdownNow(); }
    }
    @Test void queuedReportAfterWindowClosedIsAnExplicitSupplementNotASecondNormalSummary() {
        accept("HEARTBEAT",31000,"ONLINE","0"); flush(60000);
        accept("HEARTBEAT",59999,"ONLINE","0"); flush(61000); flush(62000);
        assertThat(count("REPORT_SUMMARY")).isEqualTo(1);
        assertThat(count("REPORT_LATE_SUMMARY")).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT message FROM device_event_log WHERE device_id=? AND event_type='REPORT_LATE_SUMMARY'",String.class,id))
                .contains("仅本次新增计数", "心跳 1");
    }
}
