-- 阶段 8.5 提交后跟进（决策 8.5-29）：给 inbox_message 一个单调写入序列，用作领取的稳定排序键。
--
-- 为什么需要：领取原先按 (received_at, inbox_id) 排序，而 inbox_id 是随机 UUID——
-- 同一毫秒到达的多源帧（回放数据集里每帧都有 2～4 条并列）处理顺序每次灌库都可能不同。
-- 顺序会影响"同一物理目标由哪一路先创建"：target_no 分配、target_lineage 的 CREATE 归属都会跟着变，
-- 于是同一份数据集重放得不到同一份结果，回放回归就失去意义。
--
-- 为什么不用现成的列：source_msg_id 是 VARCHAR 且按来源各自定义（协议 A 的 msgCnt、协议 C 的 msgId、
-- 雷达的 bootMicros:frameId），跨来源不可比，字典序下 "10" 还会排在 "9" 前面；
-- created_at 是毫秒 BIGINT，同样并列，而且摄取路径压根没写这一列。
--
-- 注意：本列只保证"写入先后"可复现，不代表设备的真实到达先后——
-- 两台设备在同一毫秒各报一帧，谁在前是不存在的事实。它买到的是可复现，不是正确。
ALTER TABLE inbox_message ADD COLUMN ingest_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 领取谓词是 (status, lease_until, ...) 加排序 (received_at, ingest_seq)，索引跟着排序键走。
CREATE INDEX idx_stage85_inbox_claim_order ON inbox_message (status, lease_until, received_at, ingest_seq);
