package com.uav.lowaltitude.modules.directory.infrastructure;

import java.sql.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import com.uav.lowaltitude.modules.directory.api.DirectoryDtos.*;
import com.uav.lowaltitude.modules.identity.domain.AccessDecision;

@Repository
public class DirectoryRepository {
 private final JdbcTemplate jdbc; private final ObjectMapper json;
 public DirectoryRepository(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
 private static final String ORG="SELECT o.*,COALESCE(p.organization_type,'OTHER') AS organization_type,p.address,p.credit_code,p.remarks,p.responsibilities,parent.name AS parent_name,(SELECT COUNT(*) FROM business_contact c WHERE c.org_id=o.org_id) AS contact_count,(SELECT COUNT(*) FROM flight_plan f WHERE f.operator_org_id=o.org_id OR f.source_binding_id IN(SELECT binding_id FROM plan_source_binding b WHERE b.org_id=o.org_id)) AS plan_count FROM app_org o LEFT JOIN organization_profile p ON p.org_id=o.org_id LEFT JOIN app_org parent ON parent.org_id=o.parent_id";
 private static final String CONTACT="SELECT c.*,o.name AS org_name,u.name AS user_name FROM business_contact c JOIN app_org o ON o.org_id=c.org_id LEFT JOIN app_user u ON u.user_id=c.user_id";
 private static final String BINDING="SELECT b.*,o.name AS org_name,s.name AS source_name,s.enabled AS source_enabled FROM plan_source_binding b JOIN app_org o ON o.org_id=b.org_id JOIN integration_source s ON s.source_id=b.source_id";
 private static final String SETTING="SELECT n.*,o.name AS org_name,c.name AS contact_name,c.phone AS contact_phone,c.enabled AS contact_enabled,c.valid_until AS contact_valid_until,c.verified_at AS contact_verified_at,c.roles AS contact_roles,b.org_id AS binding_org_id,b.enabled AS binding_enabled,s.name AS source_name,s.enabled AS source_enabled,r.display_name AS legacy_recipient_name FROM notification_setting n LEFT JOIN app_org o ON o.org_id=n.recipient_org_id LEFT JOIN business_contact c ON c.contact_id=n.contact_id LEFT JOIN plan_source_binding b ON b.binding_id=n.source_binding_id LEFT JOIN integration_source s ON s.source_id=b.source_id LEFT JOIN handoff_recipient r ON r.recipient_id=n.recipient_id";
 public Page<Organization> organizations(String keyword,int page,int size,AccessDecision scope){var w=orgScope("o.org_id",scope);w.search(keyword,"o.name","o.org_code");return page(ORG,w,"o.name,o.org_id",this::organization,page,size);}
 public Organization organization(String id){return one(ORG+" WHERE o.org_id=?",this::organization,id);}
 public void insertOrganization(String id,String code,OrganizationInput b,long now){jdbc.update("INSERT INTO app_org(org_id,parent_id,org_code,name,enabled,created_at,updated_at,version) VALUES(?,?,?,?,TRUE,?,?,0)",id,blank(b.parentId()),code,b.name().trim(),now,now);writeProfile(id,b);}
 public int updateOrganization(String id,OrganizationInput b,long now){int changed=jdbc.update("UPDATE app_org SET parent_id=?,name=?,updated_at=?,version=version+1 WHERE org_id=? AND version=?",blank(b.parentId()),b.name().trim(),now,id,b.expectedVersion());if(changed==1)writeProfile(id,b);return changed;}
 private void writeProfile(String id,OrganizationInput b){jdbc.update("DELETE FROM organization_profile WHERE org_id=?",id);jdbc.update("INSERT INTO organization_profile(org_id,organization_type,address,credit_code,remarks,responsibilities) VALUES(?,?,?,?,?,?)",id,b.organizationType()==null?"OTHER":b.organizationType(),blank(b.address()),blank(b.creditCode()),blank(b.remarks()),blank(b.responsibilities()));}
 public Page<Contact> contacts(String org,String keyword,Boolean enabled,int page,int size,AccessDecision scope){var w=orgScope("c.org_id",scope);w.eq("c.org_id",org);w.eq("c.enabled",enabled);w.search(keyword,"c.name","c.phone","o.name");return page(CONTACT,w,"c.name,c.contact_id",this::contact,page,size);}
 public Contact contact(String id){return one(CONTACT+" WHERE c.contact_id=?",this::contact,id);}
 public void insertContact(String id,ContactInput b,long now){jdbc.update("INSERT INTO business_contact(contact_id,org_id,name,roles,phone,email,user_id,enabled,valid_until,verified_at,verification_basis,created_at,updated_at,version) VALUES(?,?,?,CAST(? AS JSON),?,?,?,?,?,?,?,?,?,0)",id,b.orgId(),b.name().trim(),encode(b.roles()),blank(b.phone()),blank(b.email()),blank(b.userId()),b.enabled(),b.validUntil(),b.verifiedAt(),blank(b.verificationBasis()),now,now);}
 public int updateContact(String id,ContactInput b,long now){return jdbc.update("UPDATE business_contact SET org_id=?,name=?,roles=CAST(? AS JSON),phone=?,email=?,user_id=?,enabled=?,valid_until=?,verified_at=?,verification_basis=?,updated_at=?,version=version+1 WHERE contact_id=? AND version=?",b.orgId(),b.name().trim(),encode(b.roles()),blank(b.phone()),blank(b.email()),blank(b.userId()),b.enabled(),b.validUntil(),b.verifiedAt(),blank(b.verificationBasis()),now,id,b.expectedVersion());}
 public boolean userVisible(String id,AccessDecision scope){var w=orgScope("u.org_id",scope);w.eq("u.user_id",id);return count("SELECT COUNT(*) FROM app_user u"+w.sql,w.args.toArray())>0;}
 public boolean userExists(String id){return count("SELECT COUNT(*) FROM app_user WHERE user_id=? AND status='ACTIVE'",id)>0;}
 public boolean sourceExists(String id){return count("SELECT COUNT(*) FROM integration_source WHERE source_id=?",id)>0;}
 public Page<SourceBinding> bindings(String org,String source,String keyword,int page,int size,AccessDecision scope){var w=orgScope("b.org_id",scope);w.eq("b.org_id",org);w.eq("b.source_id",source);w.search(keyword,"b.external_org_code","o.name","s.name");return page(BINDING,w,"o.name,b.binding_id",this::binding,page,size);}
 public SourceBinding binding(String id){return one(BINDING+" WHERE b.binding_id=?",this::binding,id);}
 public boolean bindingSourceEnabled(String id){return count("SELECT COUNT(*) FROM plan_source_binding b JOIN integration_source s ON s.source_id=b.source_id WHERE b.binding_id=? AND b.enabled=TRUE AND s.enabled=TRUE",id)>0;}
 public void insertBinding(String id,BindingInput b,long now){jdbc.update("INSERT INTO plan_source_binding(binding_id,source_id,external_org_code,org_id,enabled,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,0)",id,b.sourceId(),b.externalOrgCode().trim(),b.orgId(),b.enabled(),now,now);}
 public int updateBinding(String id,BindingInput b,long now){return jdbc.update("UPDATE plan_source_binding SET source_id=?,external_org_code=?,org_id=?,enabled=?,updated_at=?,version=version+1 WHERE binding_id=? AND version=?",b.sourceId(),b.externalOrgCode().trim(),b.orgId(),b.enabled(),now,id,b.expectedVersion());}
 public long bindingSettings(String id){return count("SELECT COUNT(*) FROM notification_setting WHERE source_binding_id=?",id);}
 public long bindingPlans(String id){return count("SELECT COUNT(*) FROM flight_plan WHERE source_binding_id=?",id);}
 public Page<SettingRow> settings(String purpose,int page,int size,AccessDecision scope){var w=orgScope("n.recipient_org_id",scope,true);w.eq("n.purpose",purpose);return page(SETTING,w,"n.purpose,n.setting_id",this::setting,page,size);}
 public SettingRow setting(String id){return one(SETTING+" WHERE n.setting_id=?",this::setting,id);}
 public SettingRow settingForBinding(String id){return one(SETTING+" WHERE n.purpose='PLAN_FEEDBACK' AND n.source_binding_id=?",this::setting,id);}
 public SettingRow settingForRecipient(String id){return one(SETTING+" WHERE n.purpose='UAV_PUNISHMENT' AND n.recipient_id=?",this::setting,id);}
 public void insertSetting(String id,String key,String recipient,NotificationInput b,long now){jdbc.update("INSERT INTO notification_setting(setting_id,purpose,routing_key,recipient_org_id,contact_id,source_binding_id,recipient_id,channel_type,endpoint_ref,enabled,valid_until,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,0)",id,b.purpose(),key,blank(b.recipientOrgId()),blank(b.contactId()),blank(b.sourceBindingId()),recipient,b.channelType(),blank(b.endpointRef()),b.enabled(),b.validUntil(),now,now);}
 public int updateSetting(String id,String key,NotificationInput b,long now){return jdbc.update("UPDATE notification_setting SET routing_key=?,recipient_org_id=?,contact_id=?,source_binding_id=?,channel_type=?,endpoint_ref=?,enabled=?,valid_until=?,updated_at=?,version=version+1 WHERE setting_id=? AND version=?",key,blank(b.recipientOrgId()),blank(b.contactId()),blank(b.sourceBindingId()),b.channelType(),blank(b.endpointRef()),b.enabled(),b.validUntil(),now,id,b.expectedVersion());}
 public void insertRecipient(String id,String name){jdbc.update("INSERT INTO handoff_recipient(recipient_id,display_name,handoff_type,enabled,is_default,created_at,updated_at) VALUES(?,?,'UAV_PUNISHMENT',TRUE,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",id,name);}
 public void updateRecipient(String id,String name,boolean enabled){jdbc.update("UPDATE handoff_recipient SET display_name=?,enabled=?,updated_at=CURRENT_TIMESTAMP WHERE recipient_id=?",name,enabled,id);}
 public long settingHistory(String id){return count("SELECT COUNT(*) FROM handoff WHERE notification_setting_id=?",id)+count("SELECT COUNT(*) FROM flight_plan_feedback WHERE notification_setting_id=?",id)+count("SELECT COUNT(*) FROM ops_device_maintenance_notice_attempt WHERE notification_setting_id=?",id)+count("SELECT COUNT(*) FROM uav_event_advisory WHERE notification_setting_id=?",id)+count("SELECT COUNT(*) FROM uav_event_voice_advisory WHERE notification_setting_id=?",id);}
 public long settingPending(String id){return count("SELECT COUNT(*) FROM handoff h WHERE notification_setting_id=? AND EXISTS(SELECT 1 FROM handoff_delivery d WHERE d.handoff_id=h.handoff_id AND d.attempt_no=(SELECT MAX(d2.attempt_no) FROM handoff_delivery d2 WHERE d2.handoff_id=h.handoff_id) AND d.delivery_status IN('PENDING_DELIVERY','SUBMITTED'))",id)+count("SELECT COUNT(*) FROM flight_plan_feedback WHERE notification_setting_id=? AND delivery_status IN('PENDING_DELIVERY','SUBMITTED')",id)+count("SELECT COUNT(*) FROM ops_device_maintenance_notice_attempt a WHERE notification_setting_id=? AND a.attempt_no=(SELECT MAX(b.attempt_no) FROM ops_device_maintenance_notice_attempt b WHERE b.task_id=a.task_id) AND delivery_status IN('PENDING_DELIVERY','SUBMITTED')",id);}
 public long contactHistory(String id){String match="%\"contact_id\":\""+id+"\"%";return count("SELECT COUNT(*) FROM handoff WHERE recipient_snapshot LIKE ?",match)+count("SELECT COUNT(*) FROM flight_plan_feedback WHERE recipient_snapshot LIKE ?",match)+count("SELECT COUNT(*) FROM ops_device_maintenance_notice_attempt WHERE recipient_snapshot LIKE ?",match)+count("SELECT COUNT(*) FROM uav_event_advisory WHERE recipient_snapshot LIKE ?",match)+count("SELECT COUNT(*) FROM uav_event_voice_advisory WHERE recipient_snapshot LIKE ?",match);}
 public long contactPending(String id){String match="%\"contact_id\":\""+id+"\"%";return count("SELECT COUNT(*) FROM flight_plan_feedback WHERE recipient_snapshot LIKE ? AND delivery_status IN('PENDING_DELIVERY','SUBMITTED')",match)+count("SELECT COUNT(*) FROM handoff h WHERE recipient_snapshot LIKE ? AND EXISTS(SELECT 1 FROM handoff_delivery d WHERE d.handoff_id=h.handoff_id AND d.attempt_no=(SELECT MAX(d2.attempt_no) FROM handoff_delivery d2 WHERE d2.handoff_id=h.handoff_id) AND d.delivery_status IN('PENDING_DELIVERY','SUBMITTED'))",match)+count("SELECT COUNT(*) FROM ops_device_maintenance_notice_attempt a WHERE recipient_snapshot LIKE ? AND a.attempt_no=(SELECT MAX(b.attempt_no) FROM ops_device_maintenance_notice_attempt b WHERE b.task_id=a.task_id) AND delivery_status IN('PENDING_DELIVERY','SUBMITTED')",match)+count("SELECT COUNT(*) FROM uav_auto_sms_task WHERE recipient_snapshot LIKE ? AND status NOT IN('SIMULATED_DELIVERED')",match)+count("SELECT COUNT(*) FROM uav_auto_voice_task WHERE recipient_snapshot LIKE ? AND status NOT IN('SIMULATED_PLAYED')",match);}

 public long contactPlans(String id){return count("SELECT COUNT(*) FROM flight_plan WHERE pilot_contact_id=?",id);}
 public String snapshot(String table,String id){return one("SELECT recipient_snapshot FROM "+snapshotTable(table)+" WHERE "+("handoff".equals(table)?"handoff_id":"feedback_id")+"=?",(r,n)->r.getString(1),id);}
 private String snapshotTable(String table){if(!Set.of("handoff","flight_plan_feedback").contains(table))throw new IllegalArgumentException();return table;}
 public void freeze(String table,String id,RecipientSnapshot snapshot){String column="handoff".equals(table)?"handoff_id":"feedback_id";String name="handoff".equals(table)?",recipient_name_snapshot=?":"";var args=new ArrayList<Object>();args.add(encode(snapshot));args.add(snapshot.settingId());if(!name.isEmpty())args.add(snapshot.recipientName());args.add(id);jdbc.update("UPDATE "+snapshotTable(table)+" SET recipient_snapshot=?,notification_setting_id=?"+name+" WHERE "+column+"=? AND recipient_snapshot IS NULL",args.toArray());}
 private static final String SUBJECT="SELECT p.plan_id,p.plan_no,p.source_id,p.source_binding_id,p.operator_org_id,p.pilot_contact_id,p.version,p.source_mode,p.operator_name AS reported_operator_name,p.pilot_name AS reported_pilot_name,s.name AS source_name,b.org_id AS reporting_org_id,ro.name AS reporting_org_name,oo.name AS operator_org_name,c.name AS pilot_name,c.phone AS pilot_phone FROM flight_plan p LEFT JOIN integration_source s ON s.source_id=p.source_id LEFT JOIN plan_source_binding b ON b.binding_id=p.source_binding_id LEFT JOIN app_org ro ON ro.org_id=b.org_id LEFT JOIN app_org oo ON oo.org_id=p.operator_org_id LEFT JOIN business_contact c ON c.contact_id=p.pilot_contact_id";
 public SubjectRow subject(String id,AccessDecision scope,boolean lock){var w=scope("p",scope);w.eq("p.plan_id",id);if(lock){List<String> ids=jdbc.query("SELECT p.plan_id FROM flight_plan p"+w.sql+" FOR UPDATE",(r,n)->r.getString(1),w.args.toArray());if(ids.isEmpty())return null;}return one(SUBJECT+w.sql,this::subject,w.args.toArray());}
 public SubjectRow subjectInternal(String id){return one(SUBJECT+" WHERE p.plan_id=?",this::subject,id);}
 public int updateSubjects(String id,SubjectInput b,long now){return jdbc.update("UPDATE flight_plan SET source_binding_id=?,operator_org_id=?,pilot_contact_id=?,updated_at=?,version=version+1 WHERE plan_id=? AND version=?",blank(b.sourceBindingId()),blank(b.operatorOrgId()),blank(b.pilotContactId()),new Timestamp(now),id,b.expectedVersion());}
 public Page<Option> options(String kind,String org,String keyword,int page,int size,AccessDecision scope){var w=new Where();String sql,sort;
  switch(kind){
   case "organizations" -> {w=orgScope("o.org_id",scope);sql="SELECT o.org_id AS id,o.name AS label,o.org_id,NULL AS source_id FROM app_org o";w.search(keyword,"name","org_code");sort="name,org_id";}
   case "contacts" -> {w=orgScope("c.org_id",scope);sql="SELECT c.contact_id AS id,c.name AS label,c.org_id,NULL AS source_id FROM business_contact c";w.eq("c.org_id",org);w.eq("c.enabled",true);w.search(keyword,"c.name");sort="c.name,c.contact_id";}
   case "sources" -> {sql="SELECT source_id AS id,name AS label,NULL AS org_id,source_id FROM integration_source";w.search(keyword,"name","source_code");sort="name,source_id";}
   case "users" -> {w=orgScope("u.org_id",scope);sql="SELECT u.user_id AS id,u.name AS label,u.org_id,NULL AS source_id FROM app_user u";w.eq("status","ACTIVE");w.search(keyword,"name","account");sort="name,user_id";}
   case "plans" -> {sql="SELECT p.plan_id AS id,p.plan_no AS label,p.operator_org_id AS org_id,p.source_id FROM flight_plan p";w=scope("p",scope);w.search(keyword,"p.plan_no","p.operator_name");sort="p.start_at DESC NULLS LAST,p.plan_id";}
   default -> throw new IllegalArgumentException("未知目录类型");
  }
  return page(sql,w,sort,(r,n)->new Option(r.getString("id"),r.getString("label"),r.getString("org_id"),r.getString("source_id")),page,size);
 }
 public String latestEventEvaluation(String eventId){return one("SELECT r.evaluation_id FROM uav_event e JOIN alarm a ON a.alarm_id=e.alarm_id JOIN rule_evaluation r ON r.target_id=a.target_id AND r.owner_org_id=e.owner_org_id AND r.district_id=e.district_id WHERE e.event_id=? AND r.mode='ACTIVE' ORDER BY r.evaluated_at DESC,r.evaluation_id DESC FETCH FIRST 1 ROWS ONLY",(r,n)->r.getString(1),eventId);}
 public String eventPlan(String eventId,String evaluationId){if(evaluationId==null)return null;return one("SELECT r.plan_id FROM uav_event e JOIN alarm a ON a.alarm_id=e.alarm_id JOIN rule_evaluation r ON r.target_id=a.target_id AND r.alarm_id=e.alarm_id AND r.owner_org_id=e.owner_org_id AND r.district_id=e.district_id JOIN flight_plan p ON p.plan_id=r.plan_id AND p.owner_org_id=e.owner_org_id AND p.district_id=e.district_id WHERE e.event_id=? AND r.evaluation_id=? AND r.mode='ACTIVE' AND r.plan_match_code IN('FULL','PARTIAL') AND NOT EXISTS(SELECT 1 FROM rule_evaluation newer WHERE newer.target_id=r.target_id AND newer.owner_org_id=r.owner_org_id AND newer.district_id=r.district_id AND newer.mode='ACTIVE' AND (newer.evaluated_at>r.evaluated_at OR(newer.evaluated_at=r.evaluated_at AND newer.evaluation_id>r.evaluation_id)))",(r,n)->r.getString(1),eventId,evaluationId);}
 public RecipientSnapshot advisoryTaskSnapshot(String purpose,String eventId){String table="ADVISORY_SMS".equals(purpose)?"uav_auto_sms_task":"uav_auto_voice_task";String value=one("SELECT recipient_snapshot FROM "+table+" WHERE event_id=?",(r,n)->r.getString(1),eventId);return decodeSnapshot(value);}
 public void freezeAdvisoryTask(String purpose,String eventId,RecipientSnapshot snapshot){String table="ADVISORY_SMS".equals(purpose)?"uav_auto_sms_task":"uav_auto_voice_task";jdbc.update("UPDATE "+table+" SET recipient_snapshot=? WHERE event_id=? AND recipient_snapshot IS NULL",encode(snapshot),eventId);}
 public void freezeAdvisoryRecord(String purpose,String recordId,RecipientSnapshot snapshot){String table="ADVISORY_SMS".equals(purpose)?"uav_event_advisory":"uav_event_voice_advisory";jdbc.update("UPDATE "+table+" SET recipient_snapshot=?,notification_setting_id=?,recipient_name=? WHERE record_id=? AND recipient_snapshot IS NULL",encode(snapshot),snapshot.settingId(),snapshot.recipientName(),recordId);if("ADVISORY_SMS".equals(purpose))jdbc.update("UPDATE uav_event_advisory SET contact_basis=? WHERE record_id=? AND trigger_mode='AUTO'","关联计划执行飞手；模拟通道",recordId);}
 public SettingRow soleMaintenanceSetting(AccessDecision scope){var w=orgScope("n.recipient_org_id",scope);w.eq("n.purpose","DEVICE_MAINTENANCE");w.eq("n.enabled",true);var rows=jdbc.query(SETTING+w.sql+" ORDER BY n.setting_id FETCH FIRST 2 ROWS ONLY",(r,n)->setting(r,n),w.args.toArray());return rows.size()==1?rows.get(0):null;}
 public void maintenanceNotice(String taskId,RecipientSnapshot snapshot,com.uav.lowaltitude.modules.handoff.domain.HandoffChannelPort.DeliveryOutcome outcome){jdbc.update("UPDATE ops_device_maintenance_task SET recipient_snapshot=?,notification_setting_id=?,notification_delivery_status=?,notification_receipt_status=?,notification_blocked_reason=? WHERE task_id=? AND recipient_snapshot IS NULL",encode(snapshot),snapshot.settingId(),outcome.deliveryStatus(),outcome.receiptStatus(),outcome.blockedReason(),taskId);}
 public MaintenanceNotice maintenanceNotice(String taskId){return one("SELECT recipient_snapshot,notification_delivery_status,notification_receipt_status,notification_blocked_reason FROM ops_device_maintenance_task WHERE task_id=?",(r,n)->new MaintenanceNotice(decodeSnapshot(r.getString(1)),r.getString(2),r.getString(3),r.getString(4)),taskId);}
 public record MaintenanceNotice(RecipientSnapshot recipientSnapshot,String deliveryStatus,String receiptStatus,String blockedReason) { }
 public RecipientSnapshot decodeSnapshot(String value){if(value==null)return null;try{return json.readValue(value,RecipientSnapshot.class);}catch(Exception e){throw new IllegalStateException("通知对象历史快照无法读取",e);}}
 public String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("目录资料无法序列化",e);}}
 private List<String> roles(String value){try{var node=json.readTree(value);if(node.isTextual())node=json.readTree(node.asText());return json.convertValue(node,new TypeReference<List<String>>(){});}catch(Exception e){throw new IllegalStateException("联系人角色无法读取",e);}}
 private Organization organization(ResultSet r,int n)throws SQLException{return new Organization(r.getString("org_id"),r.getString("org_code"),r.getString("name"),r.getString("parent_id"),r.getString("parent_name"),r.getString("organization_type"),r.getString("address"),r.getString("credit_code"),r.getString("remarks"),r.getString("responsibilities"),r.getLong("version"),r.getLong("created_at"),r.getLong("updated_at"),r.getLong("contact_count"),r.getLong("plan_count"));}
 private Contact contact(ResultSet r,int n)throws SQLException{String id=r.getString("contact_id");return new Contact(id,r.getString("org_id"),r.getString("org_name"),r.getString("name"),roles(r.getString("roles")),r.getString("phone"),r.getString("email"),r.getString("user_id"),r.getString("user_name"),r.getBoolean("enabled"),number(r,"valid_until"),number(r,"verified_at"),r.getString("verification_basis"),r.getLong("version"),count("SELECT COUNT(*) FROM notification_setting WHERE contact_id=?",id),contactPending(id),contactHistory(id));}
 private SourceBinding binding(ResultSet r,int n)throws SQLException{return new SourceBinding(r.getString("binding_id"),r.getString("source_id"),r.getString("source_name"),r.getString("external_org_code"),r.getString("org_id"),r.getString("org_name"),r.getBoolean("enabled"),r.getLong("version"));}
 private SettingRow setting(ResultSet r,int n)throws SQLException{return new SettingRow(r.getString("setting_id"),r.getString("purpose"),r.getString("recipient_org_id"),r.getString("contact_id"),r.getString("source_binding_id"),r.getString("recipient_id"),r.getString("org_name"),r.getString("contact_name"),r.getString("contact_phone"),r.getString("source_name"),r.getString("channel_type"),r.getString("endpoint_ref"),r.getBoolean("enabled"),number(r,"valid_until"),r.getLong("version"),r.getString("legacy_recipient_name"),r.getBoolean("contact_enabled"),number(r,"contact_valid_until"),number(r,"contact_verified_at"),r.getBoolean("binding_enabled"),r.getBoolean("source_enabled"));}
 private SubjectRow subject(ResultSet r,int n)throws SQLException{return new SubjectRow(r.getString("plan_id"),r.getString("plan_no"),r.getString("source_id"),r.getString("source_name"),r.getString("source_binding_id"),r.getString("reporting_org_id"),r.getString("reporting_org_name"),r.getString("operator_org_id"),r.getString("operator_org_name"),r.getString("pilot_contact_id"),r.getString("pilot_name"),r.getString("pilot_phone"),r.getLong("version"),r.getString("source_mode"));}
 private <T> Page<T> page(String sql,Where w,String order,RowMapper<T> mapper,int page,int size){long total=count("SELECT COUNT(*) FROM ("+sql+w.sql+") directory_rows",w.args.toArray());var args=new ArrayList<>(w.args);args.add((page-1)*size);args.add(size);return new Page<>(jdbc.query(sql+w.sql+" ORDER BY "+order+" OFFSET ? ROWS FETCH NEXT ? ROWS ONLY",mapper,args.toArray()),page,size,total);}
 private <T> T one(String sql,RowMapper<T> mapper,Object...args){var rows=jdbc.query(sql,mapper,args);return rows.isEmpty()?null:rows.get(0);}
 private long count(String sql,Object...args){return jdbc.queryForObject(sql,Long.class,args);}
 private static Long number(ResultSet r,String column)throws SQLException {long value=r.getLong(column);return r.wasNull()?null:value;}
 public static String blank(String value){return value==null||value.isBlank()?null:value.trim();}
 public boolean orgVisible(String org,AccessDecision scope){if(org==null)return false;var w=orgScope("o.org_id",scope);w.eq("o.org_id",org);return count("SELECT COUNT(*) FROM app_org o"+w.sql,w.args.toArray())>0;}
 private static Where orgScope(String column,AccessDecision scope){return orgScope(column,scope,false);}
 private static Where orgScope(String column,AccessDecision scope,boolean globals){var w=new Where();switch(scope.scopeMode()){case ALL -> {} case NONE -> w.sql.append(globals?" AND "+column+" IS NULL":" AND 1=0");case ASSIGNED -> {w.sql.append(" AND (");if(globals)w.sql.append(column).append(" IS NULL OR ");w.sql.append("EXISTS(SELECT 1 FROM app_user_data_scope ds WHERE ds.user_id=? AND ds.org_id=").append(column).append("))");w.args.add(scope.userId());}}return w;}
 private static Where scope(String alias,AccessDecision scope){var w=new Where();w.sql.append(" AND ").append(alias).append(".owner_org_id IS NOT NULL AND ").append(alias).append(".district_id IS NOT NULL");switch(scope.scopeMode()) {case ALL -> {} case NONE -> w.sql.append(" AND 1=0");case ASSIGNED -> {w.sql.append(" AND EXISTS(SELECT 1 FROM app_user_data_scope gs WHERE gs.user_id=? AND gs.org_id=").append(alias).append(".owner_org_id AND gs.district_id=").append(alias).append(".district_id)");w.args.add(scope.userId());}}return w;}
 private static class Where {final StringBuilder sql=new StringBuilder(" WHERE 1=1");final List<Object> args=new ArrayList<>();void eq(String column,Object value){if(value!=null&&!"".equals(value)){sql.append(" AND ").append(column).append("=?");args.add(value);}}void search(String word,String...columns){if(word==null||word.isBlank())return;sql.append(" AND (");for(int i=0;i<columns.length;i++){if(i>0)sql.append(" OR ");sql.append("LOWER(").append(columns[i]).append(") LIKE ?");args.add("%"+word.toLowerCase(java.util.Locale.ROOT)+"%");}sql.append(")");}}
 public record SettingRow(String id,String purpose,String orgId,String contactId,String bindingId,String recipientId,
  String orgName,String contactName,String phone,String sourceName,String channelType,String endpointRef,boolean enabled,
  Long validUntil,long version,String legacyName,boolean contactEnabled,Long contactValidUntil,Long contactVerifiedAt,
  boolean bindingEnabled,boolean sourceEnabled) { }
 public record SubjectRow(String planId,String planNo,String sourceId,String sourceName,String bindingId,String reportingOrgId,
  String reportingOrgName,String operatorOrgId,String operatorOrgName,String pilotId,String pilotName,String pilotPhone,long version,String sourceMode) { }
}
