package com.uav.lowaltitude.modules.directory.application;

import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import com.uav.lowaltitude.modules.directory.api.DirectoryDtos.*;
import com.uav.lowaltitude.modules.directory.infrastructure.DirectoryRepository;
import com.uav.lowaltitude.modules.identity.application.*;
import com.uav.lowaltitude.modules.identity.domain.*;
import com.uav.lowaltitude.platform.api.ApiException;
import com.uav.lowaltitude.platform.audit.AuditService;
import com.uav.lowaltitude.platform.security.AuthContext;
import com.uav.lowaltitude.platform.time.AppClock;

@Service
public class DirectoryService {
 private final DirectoryRepository repo;private final AccessService access;private final AccessControlService businessAccess;
 private final IdempotencyGuard idempotency;private final AppClock clock;private final AuditService audit;private final NotificationDirectoryService notifications;
 public DirectoryService(DirectoryRepository repo,AccessService access,AccessControlService businessAccess,IdempotencyGuard idempotency,AppClock clock,AuditService audit,NotificationDirectoryService notifications){this.repo=repo;this.access=access;this.businessAccess=businessAccess;this.idempotency=idempotency;this.clock=clock;this.audit=audit;this.notifications=notifications;}
 @Transactional(readOnly=true) public Page<Organization> organizations(String keyword,int page,int size){read();pages(page,size);return repo.organizations(keyword,page,size,currentScope());}
 @Transactional(readOnly=true) public Organization organization(String id){read();return requireOrg(id);}
 @Transactional public Organization createOrganization(OrganizationInput body,String key){access.require("organizations.auth");if(currentScope().scopeMode()!=ScopeMode.ALL)throw new ApiException(HttpStatus.FORBIDDEN,"DIRECTORY_SCOPE_REQUIRED","新增单位需要全局单位管理范围");parent(null,body.parentId());claim(key,"organization-create",body);String id=UUID.randomUUID().toString();String code=blank(body.orgCode());if(code==null)code="ORG-"+UUID.randomUUID();try{repo.insertOrganization(id,code,body,clock.nowMillis());}catch(DataIntegrityViolationException e){throw conflict("DIRECTORY_DUPLICATE","单位编码已存在");}audit("organization_profile_created",id,"单位档案已创建");return requireOrg(id);}
 @Transactional public Organization updateOrganization(String id,OrganizationInput body,String key){access.require("organizations.auth");Organization before=requireOrg(id);version(body.expectedVersion());if(body.orgCode()!=null&&!body.orgCode().equals(before.orgCode()))throw bad("单位编码不可修改");parent(id,body.parentId());claim(key,"organization-update:"+id,body);if(repo.updateOrganization(id,body,clock.nowMillis())!=1)stale();audit("organization_profile_updated",id,"previous_version="+before.version()+"; previous_name="+before.name()+"; name="+body.name());return requireOrg(id);}
 @Transactional(readOnly=true) public Page<Contact> contacts(String org,String keyword,Boolean enabled,int page,int size){read();pages(page,size);var rows=repo.contacts(org,keyword,enabled,page,size,currentScope());return new Page<>(rows.items().stream().map(this::contactView).toList(),page,size,rows.total());}
 @Transactional(readOnly=true) public Contact contact(String id){read();return contactView(requireContact(id));}
 @Transactional public Contact createContact(ContactInput body,String key){access.require("organizations.auth");validateContact(body);claim(key,"contact-create",body);String id=UUID.randomUUID().toString();repo.insertContact(id,body,clock.nowMillis());audit("business_contact_created",id,"org_id="+body.orgId()+"; roles="+String.join(",",body.roles()));return requireContact(id);}
 @Transactional public Contact updateContact(String id,ContactInput body,String key){access.require("organizations.auth");Contact before=requireContact(id);version(body.expectedVersion());if(!Objects.equals(normalizePhone(before.phone()),normalizePhone(body.phone())))body=new ContactInput(body.orgId(),body.name(),body.roles(),body.phone(),body.email(),body.userId(),body.enabled(),body.validUntil(),null,null,body.expectedVersion());validateContact(body);if(!before.orgId().equals(body.orgId())&&(repo.contactPlans(id)>0||before.notificationCount()>0))throw conflict("CONTACT_IN_USE","联系人已用于计划或通知配置，不能直接变更所属单位；请建立正确归属的新联系人");claim(key,"contact-update:"+id,body);if(repo.updateContact(id,body,clock.nowMillis())!=1)stale();audit("business_contact_updated",id,"previous_version="+before.version()+"; enabled="+body.enabled()+"; roles="+String.join(",",body.roles()));return requireContact(id);}
 @Transactional(readOnly=true) public Page<SourceBinding> bindings(String org,String source,String keyword,int page,int size){read();pages(page,size);return repo.bindings(org,source,keyword,page,size,currentScope());}
 @Transactional public SourceBinding createBinding(BindingInput body,String key){access.require("organizations.auth");validateBinding(body);claim(key,"source-binding-create",body);String id=UUID.randomUUID().toString();try{repo.insertBinding(id,body,clock.nowMillis());}catch(DataIntegrityViolationException e){throw conflict("SOURCE_BINDING_DUPLICATE","同一技术来源的外部单位编号已登记");}audit("plan_source_binding_created",id,"source_id="+body.sourceId()+"; org_id="+body.orgId());return requireBinding(id);}
 @Transactional public SourceBinding updateBinding(String id,BindingInput body,String key){access.require("organizations.auth");SourceBinding before=requireBinding(id);version(body.expectedVersion());validateBinding(body);if((repo.bindingPlans(id)>0||repo.bindingSettings(id)>0)&&(!before.sourceId().equals(body.sourceId())||!before.orgId().equals(body.orgId())))throw conflict("SOURCE_BINDING_IN_USE","已有计划或通知配置使用此来源关联，不能替换来源或报送单位");claim(key,"source-binding-update:"+id,body);try{if(repo.updateBinding(id,body,clock.nowMillis())!=1)stale();}catch(DataIntegrityViolationException e){throw conflict("SOURCE_BINDING_DUPLICATE","同一技术来源的外部单位编号已登记");}audit("plan_source_binding_updated",id,"previous_version="+before.version()+"; enabled="+body.enabled());return requireBinding(id);}
 @Transactional(readOnly=true) public Page<Option> options(String kind,String org,String keyword,int page,int size){read();pages(page,size);if(!Set.of("organizations","contacts","sources","users","plans").contains(kind))throw bad("目录类型无效");return repo.options(kind,org,keyword,page,size,currentScope());}
 @Transactional(readOnly=true) public Subjects subjects(String id){var row=repo.subject(id,subjectScope(),false);if(row==null)throw missing("计划不存在或不可见");return subjectView(row);}
 @Transactional public Subjects updateSubjects(String id,SubjectInput body,String key){access.require("organizations.auth");var row=repo.subject(id,currentScope(),true);if(row==null)throw missing("计划不存在或不可见");version(body.expectedVersion());if(row.version()!=body.expectedVersion())stale();String bindingId=blank(body.sourceBindingId()),operatorId=blank(body.operatorOrgId()),pilotId=blank(body.pilotContactId());
  if(bindingId!=null){SourceBinding binding=requireBinding(bindingId);if(!binding.enabled()||!repo.bindingSourceEnabled(bindingId)||!Objects.equals(binding.sourceId(),row.sourceId()))throw conflict("PLAN_SOURCE_MISMATCH","报送单位关联必须来自该计划已启用的技术来源");}
  if(operatorId!=null)requireOrg(operatorId);
  if(pilotId!=null){Contact pilot=requireContact(pilotId);if(operatorId==null||!operatorId.equals(pilot.orgId())||!pilot.roles().contains("PILOT"))throw conflict("PLAN_PILOT_MISMATCH","执行飞手必须是该运营单位的飞手联系人");if(!active(pilot))throw conflict("CONTACT_UNAVAILABLE","执行飞手联系人当前不可用");}
  claim(key,"plan-subjects:"+id,body);if(repo.updateSubjects(id,body,clock.nowMillis())!=1)stale();audit("plan_subjects_associated",id,"previous_version="+row.version()+"; source_binding_id="+bindingId+"; operator_org_id="+operatorId+"; pilot_contact_id="+pilotId+"; reason="+body.reason());return subjectView(repo.subject(id,currentScope(),false));
 }
 private Subjects subjectView(DirectoryRepository.SubjectRow row){boolean bound=row.bindingId()!=null&&row.operatorOrgId()!=null&&row.pilotId()!=null;String status=bound?"LINKED":row.bindingId()!=null||row.operatorOrgId()!=null||row.pilotId()!=null?"PARTIAL":"UNLINKED";if(row.pilotId()!=null){Contact pilot=repo.contact(row.pilotId());if(pilot==null||!active(pilot)||!pilot.roles().contains("PILOT"))status="PARTIAL";}if(row.bindingId()!=null&&!repo.bindingSourceEnabled(row.bindingId()))status="PARTIAL";return new Subjects(row.planId(),row.planNo(),row.sourceId(),row.sourceName(),row.bindingId(),row.reportingOrgId(),row.reportingOrgName(),row.operatorOrgId(),row.operatorOrgName(),row.pilotId(),row.pilotName(),NotificationDirectoryService.mask(row.pilotPhone()),status,row.version(),notifications.forPlan(row.planId()));}
 private Contact contactView(Contact c){try{access.require("organizations.read");return c;}catch(ApiException e){if(e.getStatus()!=HttpStatus.FORBIDDEN)throw e;return new Contact(c.contactId(),c.orgId(),c.orgName(),c.name(),c.roles(),NotificationDirectoryService.mask(c.phone()),null,null,null,c.enabled(),c.validUntil(),c.verifiedAt(),null,c.version(),c.notificationCount(),c.pendingCount(),c.historyCount());}}
 private void validateContact(ContactInput b){requireOrg(b.orgId());if(new HashSet<>(b.roles()).size()!=b.roles().size()||!Set.of("PILOT","PLAN_LIAISON","UNIT_LIAISON","MAINTENANCE").containsAll(b.roles()))throw bad("联系人角色无效或重复");if(blank(b.userId())!=null&&(!repo.userExists(b.userId())||!repo.userVisible(b.userId(),currentScope())))throw conflict("USER_UNAVAILABLE","关联账号不存在或不可用");if(blank(b.phone())!=null&&!b.phone().matches("[+0-9 ()-]{6,64}"))throw bad("联系电话格式不正确");if(b.verifiedAt()!=null&&(b.verifiedAt()>clock.nowMillis()||blank(b.verificationBasis())==null))throw bad("联系方式核验需要已发生的核验时间与依据");}
 private void validateBinding(BindingInput b){requireOrg(b.orgId());if(!repo.sourceExists(b.sourceId()))throw missing("技术来源不存在");}
 private void parent(String id,String parentId){String next=blank(parentId);var seen=new HashSet<String>();while(next!=null){if(next.equals(id)||!seen.add(next))throw bad("上级单位不能形成循环");Organization parent=requireOrg(next);next=parent.parentId();}}
 private Organization requireOrg(String id){Organization org=repo.organization(id);if(org==null||!repo.orgVisible(id,currentScope()))throw missing("单位不存在或不在管理范围内");return org;}
 private Contact requireContact(String id){Contact c=repo.contact(id);if(c==null||!repo.orgVisible(c.orgId(),currentScope()))throw missing("联系人不存在或不在管理范围内");return c;}
 private SourceBinding requireBinding(String id){SourceBinding b=repo.binding(id);if(b==null||!repo.orgVisible(b.orgId(),currentScope()))throw missing("来源单位关联不存在或不在管理范围内");return b;}
 private boolean active(Contact c){return c.enabled()&&(c.validUntil()==null||c.validUntil()>clock.nowMillis());}
 private AccessDecision subjectScope(){try{access.require("organizations.read");return currentScope();}catch(ApiException e){if(e.getStatus()!=HttpStatus.FORBIDDEN)throw e;return businessAccess.require(PermissionCode.FLIGHT_READ);}}
 private AccessDecision currentScope(){var actor=AuthContext.require();return new AccessDecision(actor.userId(),ScopeMode.valueOf(actor.scopeMode()));}
 private void read(){try{access.require("organizations.read");}catch(ApiException e){if(e.getStatus()!=HttpStatus.FORBIDDEN)throw e;access.require("notificationSettings.read");}}
 private void claim(String key,String operation,Object body){idempotency.claim(key,operation+":"+repo.encode(body));}
 private void audit(String action,String id,String detail){var actor=AuthContext.require();audit.record(actor.userId(),actor.account(),actor.roleCode(),"organizations",action,"business_directory",id,detail,"SUCCESS","","");}
 private static String normalizePhone(String value){return value==null?null:value.replaceAll("[ ()-]", "");}
 private static String blank(String value){return DirectoryRepository.blank(value);}
 public static void pages(int p,int s){if(p<1||s<1||s>100||(long)(p-1)*s>Integer.MAX_VALUE)throw bad("page从1开始，size必须为1至100");}
 private static void version(Long version){if(version==null)throw bad("修改资料需要expected_version");}
 private static void stale(){throw conflict("VERSION_CONFLICT","资料已更新，请刷新后重试");}
 private static ApiException bad(String message){return new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR",message);}
 private static ApiException missing(String message){return new ApiException(HttpStatus.NOT_FOUND,"DIRECTORY_NOT_FOUND",message);}
 private static ApiException conflict(String code,String message){return new ApiException(HttpStatus.CONFLICT,code,message);}
}
