<script setup>
import { userFacingMessage } from '@/utils/userMessages';
import { computed, ref } from 'vue';
import { formatTime } from '@/utils/format.js';
import { maintenanceMeta } from './useMaintenanceWorkflow.js';
import { useAuthStore } from '@/stores/auth.js';
const props = defineProps({ workflow: Object, section: { type: String, default: 'context' }, busy: Boolean, locked: Boolean, actionError: String, pending: Boolean });
const emit = defineEmits(['action', 'retry', 'refresh', 'report', 'recover-incident']);
const note = ref(''), details = ref(false);
const meta = computed(() => maintenanceMeta(props.workflow?.state));
const task = computed(() => props.workflow?.task || {});
const recentEvents = computed(() => [...(props.workflow?.events || [])].reverse());
const allowed = action => !props.busy && !props.pending && !props.locked && props.workflow?.allowed_actions?.includes(action);
const auth = useAuthStore();
// BUG-02：没有设备实时监测的操作权限时后端不给任何待办动作，按钮只会灰着；这里说清原因。按钮能否点仍只看 allowed_actions。
const permissionHint = computed(() => ['PENDING', 'PROCESSING', 'PENDING_VERIFICATION'].includes(props.workflow?.state) && !auth.hasPermission('monitoring.op')
  ? '当前账号只能查看这条运维待办：开始处理、保存进展、提交恢复核验和完成待办需要“设备实时监测”的操作权限，请联系管理员在角色权限中开通。' : '');
const primary = computed(() => ({ PENDING:['START','开始处理'],PROCESSING:['SUBMIT_VERIFICATION','提交恢复核验'],PENDING_VERIFICATION:['VERIFY_RECOVERY','执行恢复核验'] })[props.workflow?.state]);
function save() { if (allowed('SAVE_PROGRESS') && note.value.trim().length <= 1000) emit('action', 'SAVE_PROGRESS', { note: note.value.trim() }, () => { note.value = ''; }); }
</script>

<template>
  <el-card v-if="section==='context'" class="maintenance-context">
    <div class="maintenance-heading"><div><div class="maintenance-heading-label"><b>关联运维待办</b><el-tag :type="meta.tone" size="small">{{ meta.label }}</el-tag><el-tag v-if="task.simulated" type="info" size="small">模拟设备</el-tag></div><p class="maintenance-device">{{ task.device_name }} <span>{{ task.device_no }}</span></p></div><div class="maintenance-actions"><el-button :disabled="busy || pending" @click="emit('refresh')">刷新待办</el-button><el-button v-if="primary" type="primary" :loading="busy" :disabled="!allowed(primary[0])" @click="emit('action', primary[0])">{{ primary[1] }}</el-button></div></div>
    <p class="maintenance-reason"><span>异常说明</span>{{ task.reason }}</p>
    <div class="maintenance-meta"><span>上报时间 <b>{{ formatTime(task.reported_at) }}</b></span><span>关联计划 <b>{{ task.plan_no || '无查看权限' }}</b></span><span>处理人 <b>{{ workflow.assigned_to_name || '待接手' }}</b></span><el-button link type="primary" @click="details=true">查看上报详情</el-button></div>
    <el-steps v-if="workflow.state!=='LEGACY_HANDLED'" :active="meta.step" finish-status="success" align-center class="maintenance-steps"><el-step title="待处理" /><el-step title="处理中" /><el-step title="待恢复核验" /><el-step title="已完成" /></el-steps>
    <el-alert v-else title="此记录为旧流程已反馈，不能作为设备恢复凭据。" type="info" :closable="false" show-icon />
    <el-alert v-if="workflow.blocked_reason" :title="userFacingMessage(workflow.blocked_reason)" type="warning" :closable="false" show-icon />
    <el-alert v-if="permissionHint" class="maintenance-permission" :title="permissionHint" type="info" :closable="false" show-icon />
    <div v-if="workflow.open_incidents?.length" class="maintenance-incident-list"><p class="muted">设备尚有未恢复的异常事件。支持恢复核验的事件可在此核查，核验后再确认待办恢复。</p><article v-for="incident in workflow.open_incidents" :key="incident.incident_id"><span>{{ incident.reason }}</span><el-button v-if="incident.allowed_actions?.includes('VERIFY_RECOVERY') && !['COMPLETED','LEGACY_HANDLED'].includes(workflow.state)" :disabled="busy || locked || pending" link type="primary" @click="emit('recover-incident',incident)">核验事件恢复</el-button><small v-else class="muted">{{ incident.stage==='REBOOTING' ? '等待设备指令回执' : '需先按设备异常流程处理' }}</small></article></div>
    <el-alert v-if="actionError" :title="actionError" type="error" :closable="false" show-icon />
    <el-button v-if="pending" type="primary" :loading="busy" @click="emit('retry')">按原请求重试确认</el-button>
    <div v-if="workflow.recovery" class="maintenance-recovery"><el-tag :type="workflow.recovery.result==='PASS'?'success':'warning'">{{ workflow.recovery.result==='PASS'?'恢复核验通过':workflow.recovery.result==='FAIL'?'恢复核验未通过':'恢复状态未知' }}</el-tag><span>{{ workflow.recovery.reason }}</span><small>{{ formatTime(workflow.recovery.checked_at) }}</small></div>
    <div v-if="workflow.state==='PENDING_VERIFICATION'" class="maintenance-actions recovery-actions"><el-button :disabled="!allowed('RESUME')" @click="emit('action','RESUME')">继续处理</el-button><el-button v-if="workflow.allowed_actions?.includes('COMPLETE')" type="primary" :disabled="!allowed('COMPLETE')" @click="emit('action','COMPLETE')">完成待办</el-button></div>
    <el-dialog v-model="details" title="运维待办上报详情" width="min(660px,94vw)"><el-descriptions :column="1" border><el-descriptions-item label="待办编号">{{ task.task_id }}</el-descriptions-item><el-descriptions-item label="上报人">{{ task.reported_by_name }}</el-descriptions-item><el-descriptions-item label="异常说明">{{ task.reason }}</el-descriptions-item><el-descriptions-item label="首次上报连接状态">{{ ({ONLINE:'在线',OFFLINE:'离线',DISABLED:'停用',UNKNOWN:'未知'})[task.connectivity] || task.connectivity || '未知' }}</el-descriptions-item><el-descriptions-item label="首次上报健康状态">{{ ({GOOD:'良好',BAD:'异常',DEGRADED:'异常',UNKNOWN:'未知'})[task.health_code] || '未知' }}</el-descriptions-item><el-descriptions-item label="状态上报时间">{{ formatTime(task.observed_at) }}</el-descriptions-item><el-descriptions-item v-if="task.handling_note" label="处理结果">{{ task.handling_note }}</el-descriptions-item></el-descriptions><p class="muted">此处展示上报快照，当前设备状态以实时读取为准。完整通知记录可从原待办列表查看。</p><template #footer><el-button @click="details=false">关闭</el-button></template></el-dialog>
  </el-card>
  <el-card v-else class="maintenance-progress"><template #header><div class="table-toolbar"><b>运维处理记录</b><span class="muted">{{ task.device_name }}</span></div></template>
    <div class="maintenance-progress-grid"><div><template v-if="workflow.state==='PROCESSING'"><label for="maintenance-note">本次处理说明（选填）</label><el-input id="maintenance-note" v-model="note" type="textarea" :rows="4" :maxlength="1000" show-word-limit :disabled="!allowed('SAVE_PROGRESS')" placeholder="可补充检查项、处理措施与后续安排" /><div class="maintenance-save"><span class="muted">保存进展不会结束待办。</span><el-button :loading="busy" :disabled="!allowed('SAVE_PROGRESS') || note.trim().length>1000" @click="save">保存进展</el-button></div></template><el-alert v-else :title="workflow.state==='PENDING'?'接手待办后可记录排查和处理进展。':workflow.state==='PENDING_VERIFICATION'?'等待恢复核验；核验失败可继续处理，历史记录保留。':'处理记录只读保留。'" type="info" :closable="false" />
      <h3>关联调测报告</h3><div v-for="item in workflow.commission_tasks || []" :key="item.commission_id" class="maintenance-report"><span>{{ item.commission_no || item.commission_id }}</span><el-tag v-if="item.simulated" size="small" type="info">模拟</el-tag><el-button link type="primary" :disabled="!['PASSED','FAILED','UNTESTABLE'].includes(item.status)" @click="emit('report',item)">查看报告</el-button></div><p v-if="!workflow.commission_tasks?.length" class="muted">暂无关联调测任务。支持调测的设备可在上方创建或关联任务。</p>
    </div><div class="maintenance-timeline"><h3>处理时间线</h3><el-timeline><el-timeline-item v-for="event in recentEvents" :key="event.event_id" :timestamp="formatTime(event.occurred_at)"><b>{{ ({START:'开始处理',SAVE_PROGRESS:'处理进展',SUBMIT_VERIFICATION:'提交恢复核验',VERIFY_RECOVERY:'执行恢复核验',COMPLETE:'待办已完成',RESUME:'继续处理',LINK_COMMISSION:'关联调测任务',REPORTED:'异常已上报'})[event.action] || event.action }}</b><span class="muted"> · {{ event.actor_name }}</span><p>{{ event.note }}</p></el-timeline-item><el-timeline-item :timestamp="formatTime(task.reported_at)"><b>异常已上报</b><p>{{ task.reported_by_name }} · {{ task.reason }}</p></el-timeline-item></el-timeline></div></div>
  </el-card>
</template>

<style scoped>
.maintenance-context{border-color:#cddff6!important;background:linear-gradient(100deg,#f8fbff,#fff 65%)!important}.maintenance-heading{display:flex;justify-content:space-between;gap:12px;align-items:center}.maintenance-heading-label,.maintenance-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.maintenance-device{margin:8px 0 0;font-size:14px}.maintenance-device span{margin-left:10px;font-size:12px;color:#718097}.maintenance-reason{font-size:13px;line-height:1.8;color:#526780;margin:18px 0 10px}.maintenance-reason>span{margin-right:14px;color:#8492a6}.maintenance-meta{display:flex;gap:12px 22px;align-items:center;flex-wrap:wrap;font-size:12px;color:#8492a6}.maintenance-meta b{font-weight:400;color:#405069;margin-left:6px}.maintenance-meta .el-button{margin-left:auto}.maintenance-steps{margin-top:18px;padding-top:18px;border-top:1px solid #e5edf7}.maintenance-steps :deep(.el-step__title){font-size:12px}.maintenance-context :deep(.el-alert){margin-top:12px}.maintenance-context :deep(.el-alert__title){overflow-wrap:anywhere}.maintenance-recovery{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:12px;line-height:1.8;margin-top:15px;color:#526780}.maintenance-recovery small{color:#8492a6}.recovery-actions{justify-content:flex-end;margin-top:14px}.maintenance-progress-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:24px}.maintenance-progress label{display:block;margin-bottom:9px;font-size:13px;color:#526780}.maintenance-save,.maintenance-report{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:12px}.maintenance-progress h3{font-size:13px;color:#526780;margin:18px 0 14px}.maintenance-timeline{border-left:1px solid #edf0f5;padding-left:22px}.maintenance-timeline h3{margin-top:0}.maintenance-timeline p{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;color:#718097;line-height:1.7;margin:5px 0}.maintenance-report{font-size:12px}.maintenance-report>span{overflow-wrap:anywhere}.maintenance-progress :deep(.el-timeline){padding-left:4px}.maintenance-actions :deep(.el-button){margin-left:0}
@media(max-width:900px){.maintenance-progress-grid{grid-template-columns:1fr}.maintenance-timeline{border-left:0;border-top:1px solid #edf0f5;padding:18px 0 0}.maintenance-heading{align-items:flex-start;flex-wrap:wrap}.maintenance-meta .el-button{margin-left:0}}
</style>
<style scoped>.maintenance-incident-list{margin-top:14px}.maintenance-incident-list article{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap;padding:10px 0;border-bottom:1px solid #edf0f5;font-size:12px;color:#526780}.maintenance-incident-list article>span{overflow-wrap:anywhere;flex:1;min-width:160px}</style>
